query Pages5($id: Int!, $getLatest: Boolean) {
  pages {
    history(id: $id, getLatest: $getLatest) {
      trail {
        versionId
        versionDate
        authorId
        authorName
        actionType
        valueBefore
        
        valueAfter
        version
      }
    }
  }
}
