query Pages6($pageId: Int!, $versionId: Int!) {
  pages {
    version(pageId: $pageId, versionId: $versionId) {
      action
      content
      contentType
      createdAt
      versionDate
      description
      locale
      pageId
      path
      publishEndDate
      publishStartDate
      title
      versionId
      version
    }
  }
}
